services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 5450:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /home/satplat/deployDB/tic-tac-toe-db:/db/

volumes:
  postgres_data:
